from django.core.exceptions import ValidationError


def validate_version(value):
    print(value)

